export const staticContacts = [
    {
        first_name: 'John',
        last_name: 'Doe',
        title: 'Manager',
        email: 'john.doe@example.com',
        phone_1_number: '123-456-7890',
        phone_2_number: '987-654-3210',
        background: 'Experienced sales manager.',
    },
    {
        first_name: 'Jane',
        last_name: 'Smith',
        title: 'Developer',
        email: 'jane.smith@example.com',
        phone_1_number: '234-567-8901',
        phone_2_number: '876-543-2109',
        background: 'Skilled software engineer with a focus on frontend development.',
    },
    {
        first_name: 'Alice',
        last_name: 'Johnson',
        title: 'HR Specialist',
        email: 'alice.johnson@example.com',
        phone_1_number: '345-678-9012',
        phone_2_number: '765-432-1098',
        background: 'HR professional with experience in recruitment and employee relations.',
    },
    {
        first_name: 'Bob',
        last_name: 'Brown',
        title: 'Product Manager',
        email: 'bob.brown@example.com',
        phone_1_number: '456-789-0123',
        phone_2_number: '654-321-0987',
        background: 'Product manager with expertise in mobile applications.',
    },
    {
        first_name: 'Charlie',
        last_name: 'Davis',
        title: 'Sales Representative',
        email: 'charlie.davis@example.com',
        phone_1_number: '567-890-1234',
        phone_2_number: '543-210-9876',
        background: 'Sales expert with a focus on B2B solutions.',
    },
    {
        first_name: 'David',
        last_name: 'Martinez',
        title: 'Marketing Director',
        email: 'david.martinez@example.com',
        phone_1_number: '678-901-2345',
        phone_2_number: '432-109-8765',
        background: 'Experienced marketing leader specializing in digital campaigns.',
    },
    {
        first_name: 'Eva',
        last_name: 'Garcia',
        title: 'Graphic Designer',
        email: 'eva.garcia@example.com',
        phone_1_number: '789-012-3456',
        phone_2_number: '321-098-7654',
        background: 'Creative graphic designer with a passion for brand identity.',
    },
    {
        first_name: 'Frank',
        last_name: 'Wilson',
        title: 'Data Analyst',
        email: 'frank.wilson@example.com',
        phone_1_number: '890-123-4567',
        phone_2_number: '210-987-6543',
        background: 'Data analyst with experience in business intelligence tools.',
    },
];

export const staticCompanies = [
    {
        name: "Alpha Technologies",
        website: "https://www.alphatech.com",
        phone_number: "(123) 456-7890",
        address: "123 Alpha Street",
        zipcode: "10001",
        city: "New York",
        stateAbbr: "NY",
        revenue: "$10M",
        country: "USA",
        description: "Leading provider of AI-driven solutions."
    },
    {
        name: "Beta Innovations",
        website: "https://www.betainno.com",
        phone_number: "(987) 654-3210",
        address: "456 Beta Avenue",
        zipcode: "90001",
        city: "Los Angeles",
        stateAbbr: "CA",
        revenue: "$100M",
        country: "USA",
        description: "Pioneers in blockchain and security technologies."
    },
    {
        name: "Gamma Solutions",
        website: "https://www.gammasol.com",
        phone_number: "(555) 123-4567",
        address: "789 Gamma Blvd",
        zipcode: "60601",
        city: "Chicago",
        stateAbbr: "IL",
        revenue: "$1B",
        country: "USA",
        description: "Cloud computing and big data experts."
    },
    {
        name: "Delta Systems",
        website: "https://www.deltasys.com",
        phone_number: "(321) 654-9870",
        address: "101 Delta Road",
        zipcode: "75001",
        city: "Dallas",
        stateAbbr: "TX",
        revenue: "$1M",
        country: "USA",
        description: "Innovators in embedded systems and IoT."
    },
    {
        name: "Epsilon Networks",
        website: "https://www.epsilonnet.com",
        phone_number: "(777) 888-9999",
        address: "202 Epsilon Lane",
        zipcode: "94101",
        city: "San Francisco",
        stateAbbr: "CA",
        revenue: "$10M",
        country: "USA",
        description: "Next-gen networking and cybersecurity solutions."
    }
];